---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

clone:
  image: reg.int.it2000.com.cn/devops/git
  tags: true
  skip_verify: true

steps:
  - name: compile and test
    image: reg.int.it2000.com.cn/library/gradle:7.1-jdk11
    volumes:
      - name: gradle
        path: /home/gradle/.gradle
      - name: certs
        path: /etc/ssl/certs
    environment:
      ORACLE_USER: cdjc
      ORACLE_PASS: cdjc
    commands:
      - gradle clean
      - gradle test

  - name: build
    image: reg.int.it2000.com.cn/library/gradle:7.1-jdk11
    volumes:
      - name: gradle
        path: /home/gradle/.gradle
      - name: certs
        path: /etc/ssl/certs
    commands:
      - gradle build
      - gradle check
    #when:
    #  event: tag

  - name: release
    image: plugins/gitea-release
    volumes:
      - name: certs
        path: /etc/ssl/certs
    settings:
      title: 0.0.16
      api_key: fe1e1a8dd77de7452a3f473984c7ac6fe6c5abaf
      base_url: https://gitea.int.it2000.com.cn
      files:
        - build/distributions/*
      checksum:
        - sha256
    when:
      event: tag

  - name: publish
    image: plugins/docker
    volumes:
      - name: certs
        path: /etc/ssl/certs
      - name: docker
        path: /var/run/docker.sock
    settings:
      repo: reg.int.it2000.com.cn/changde/estt-calc
      registry: reg.int.it2000.com.cn
      insecure: true
      tags: [ "${DRONE_COMMIT_SHA:0:4}","latest" ]
      #      auth: ZmVuZ3poaXFpYW5nOmFkbWluZ3p6bg==
      username:
        from_secret: registry_user
      password:
        from_secret: registry_pass
    when:
      branch:
        - develop

  - name: release-publish
    image: plugins/docker
    volumes:
      - name: certs
        path: /etc/ssl/certs
      - name: docker
        path: /var/run/docker.sock
    settings:
      repo: reg.int.it2000.com.cn/changde/estt-calc
      registry: reg.int.it2000.com.cn
      tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
      insecure: true
      auto_tag: true
      username: 
        from_secret: registry_user
      password:
        from_secret: registry_pass
    
    when:
      event: tag

volumes:
  - name: gradle
    host:
      path: /opt/gradle
  - name: certs
    host:
      path: /etc/ssl/certs
  - name: docker
    host:
      path: /var/run/docker.sock
