---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

clone:
  image: reg.int.it2000.com.cn/devops/git
  tags: true
  skip_verify: true

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
      - /root/.gradle
    volumes:
      - name: cache
        path: /cache

    

  - name: compile and test
    image: reg.int.it2000.com.cn/library/gradle:8.1-jdk17
    volumes:
      - name: cache
        path: /root/.gradle
      - name: certs
        path: /etc/ssl/certs/ca-certificates.crt
    environment:
      ORACLE_USER: cdjc
      ORACLE_PASS: cdjc
    commands:
      - gradle clean
      - gradle test

  - name: build
    image: reg.int.it2000.com.cn/library/gradle:8.1-jdk17
    volumes:
      - name: cache
        path: /root/.gradle
      - name: certs
        path: /etc/ssl/certs/ca-certificates.crt
    commands:
      - gradle build
      - gradle check
    #when:
    #  event: tag

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - /root/.gradle
    volumes:
      - name: cache
        path: /cache

  - name: release
    image: plugins/gitea-release
    volumes:
      - name: certs
        path: /etc/ssl/certs/ca-certificates.crt
    settings:
      title: 0.0.19
      api_key: 5e6aef8f90828ea3d9098a9f2967c14198aaf6d4
      base_url: https://gitea.int.it2000.com.cn
      files:
        - build/distributions/*
      checksum:
        - sha256
    when:
      event: tag

  - name: publish
    image: plugins/docker
    volumes:
      - name: certs
        path: /etc/ssl/certs/ca-certificates.crt
      - name: docker
        path: /var/run/docker.sock

    settings:
      repo: reg.int.it2000.com.cn/changde/estt-calc
      registry: reg.int.it2000.com.cn
      insecure: true
      tags: [ "${DRONE_COMMIT_SHA:0:4}","latest" ]
      #      auth: ZmVuZ3poaXFpYW5nOmFkbWluZ3p6bg==
      username:
        from_secret: registry_user
      password:
        from_secret: registry_pass
    when:
      branch:
        - develop

  - name: release-publish
    image: plugins/docker
    volumes:
      - name: certs
        path: /etc/ssl/certs/ca-certificates.crt
      - name: docker
        path: /var/run/docker.sock
    settings:
      repo: reg.int.it2000.com.cn/changde/estt-calc
      registry: reg.int.it2000.com.cn
      tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
      insecure: true
      auto_tag: true
      username:
        from_secret: registry_user
      password:
        from_secret: registry_pass
    when:
      event: tag



volumes:
  - name: cache
    host:
      path: /opt/cache/gradle
  - name: certs
    host:
      path: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
  - name: docker
    host:
      path: /var/run/docker.sock