micronaut:
  application:
    name: esttCalc
datasources:
  gzzn :
    url: jdbc:oracle:thin:@bj023.int.it2000.com.cn:1521:orcl
    driverClassName: oracle.jdbc.OracleDriver
    username: 'cdjc'
    password: 'cdjc'
    dialect: Oracle

default:
  maxHistoryDelay: 120
  minHistoryFlight: 20
  dateFormat: 'yyMMdd'
