micronaut:
  application:
    name: estt-calc
datasources:
  gzzn:
    url: "jdbc:oracle:thin:@${ORACLE_HOST:bj024.int.it2000.com.cn}:${ORACLE_PORT:1521}:${ORACLE_SID:orcl}"
    driverClassName: oracle.jdbc.OracleDriver
    username: ${ORACLE_USER:cdjc}
    password: ${ORACLE_PASS:cdjc}
    dialect: Oracle

default:
  maxHistoryDelay: ${MAX_DELAY:120}
  minHistoryFlight: ${MIN_HISTORY:20}
  dateFormat: 'yyMMdd'
